#!/usr/bin/env bash
# Install nginx on your web-01 server, should be listening on port 80, curl must return the string Holberton School
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School for the win!" | cat > /usr/share/nginx/html/index.html
sudo service nginx restart
