#!/usr/bin/env bash
# Configures your Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R ubuntu:ubuntu /var/www/
sudo chown -R ubuntu:ubuntu /etc/nginx/
if [ -f /var/www/html/index.nginx-debian.html ]; then
	sudo echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html
fi
if [ -f /usr/share/nginx/html/index.html ]; then
	sudo echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
fi
if [ -f /etc/nginx/sites-enabled/default ]; then
	sed -i -E 's/listen [0-9]+ default_server/listen 80 defaut_server/g' /etc/nginx/sites-enabled/default
	sed -i -E 's/listen \[::\]:[0-9]+ default_server/listen [::]:80 defaut_server/g' /etc/nginx/sites-enabled/default
fi
if [ -f /etc/nginx/nginx.conf ]; then
	sed -i -E 's/listen [0-9]+ default_server/listen 80 defaut_server/g' /etc/nginx/nginx.conf
	sed -i -E 's/listen \[::\]:[0-9]+ default_server/listen [::]:80 defaut_server/g' /etc/nginx/nginx.conf
fi
sudo /etc/init.d/nginx start
# Configures your Nginx server so that /redirect_me is redirecting to another page.
config_file=/etc/nginx/sites-enabled/default
sudo sed -i -E "0,/listen \[::]:[0-9]+ .+;/s//& \n rewrite \^\/redirect_me\/\$ https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent\;/" "$config_file"
sudo /etc/init.d/nginx restart
