#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
sudo apt-get update -y
sudo apt-get install nginx -y
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/page404.html
redirectme="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
str="\n\terror_page 404 \/ page404.html;\n\tlocation = \/page404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$redirectme$str/" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx start
sudo /etc/init.d/nginx restart
