#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt update -y
sudo apt-get install -y haproxy=1.6.\*
setup="
frontend firstbalance
	  bind *:80
	  mode http
          default_backend webservers

backend webservers
	balance roundrobin
	server 149-web-01 34.139.184.21:80 check
	server 149-web-02 34.74.230.21:80 check
"
sudo echo "$setup" | sudo tee /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo service haproxy start
